src/nodes/SVGNode.php, src/nodes/shapes/SVGCircle.php, src/nodes/shapes/SVGEllipse.php, src/nodes/shapes/SVGLine.php, src/nodes/shapes/SVGPolygon.php, src/nodes/shapes/SVGPolyline.php, src/nodes/shapes/SVGRect.php, src/nodes/structures/SVGDocumentFragment.php
This merge request just adds a `return $this` to SVG node property setters. This lets one chain calls in a fluent style, e.g. I can now write:
```php
$doc->addChild(
(new SVGCircle(200, 200, 10))
->setStyle('fill-opacity', 0.01)
->setStyle('stroke-width', 1)
->setStyle('stroke', 'currentColor')
);
```
instead of the more verbose
```php
$circle = new SVGCircle(200, 200, 10);
$circle->setStyle('fill-opacity', 0.01);
$circle->setStyle('stroke-width', 1);
$circle->setStyle('stroke', 'currentColor');
$doc->addChild($circle);
```
Since node property setters don't currently return anything, this will not break any code using the current API, which will continue to function unaffected, while enabling the option to use a fluent interface if desired.
`
=> Implement fluent interfaces on SVG object setters

src/Nodes/SVGNode.php, src/Nodes/SVGNodeContainer.php, src/Nodes/Shapes/SVGCircle.php, src/Nodes/Shapes/SVGEllipse.php, src/Nodes/Shapes/SVGLine.php, src/Nodes/Shapes/SVGPath.php, src/Nodes/Shapes/SVGPolygon.php, src/Nodes/Shapes/SVGPolygonalShape.php, src/Nodes/Shapes/SVGPolyline.php, src/Nodes/Shapes/SVGRect.php, src/Nodes/Structures/SVGDocumentFragment.php, src/Nodes/Structures/SVGGroup.php, src/Reading/SVGReader.php, tests/SVGImageTest.php
Most nodes now use the central `SVGNode::attributes` for storing their special properties, e.g. SVGRect doesn't use separate x, y, width and height properties, but instead just has the respective getters and setters act as covers for `getAttribute()` and `setAttribute()`.
Additionally, tag names are stored in new 'TAG_NAME' constants for every SVGNode subclass. They are used directly by SVGNode, and so passing the names via the super constructor has become unnecessary.
This has a multitude of benefits:
* Every attribute is serialized automatically.
* The "special" properties aren't so special any more; they are treated like every other, with support for `getAttribute(...)` and so on.
Moreover, SVGNode subclasses need not override `constructFromAttributes(...)` as before, provided that …
=> Special prop's backed by `SVGNode::attributes` (simpler read/write)

src/Rasterization/Renderers/SVGEllipseRenderer.php, src/Rasterization/Renderers/SVGLineRenderer.php, src/Rasterization/Renderers/SVGPolygonRenderer.php, src/Rasterization/Renderers/SVGRectRenderer.php, src/Rasterization/SVGRasterizer.php, src/SVGImage.php
This closes #20. `preserveAspectRatio` is not yet supported, but `viewBox` itself behaves correctly both with and without accompanying `width`/`height` attributes.
=> Add viewBox support to rasterization

src/Nodes/Shapes/SVGPolygonalShape.php
Sometimes $attrs['points'] contain trailing spaces in the end or beginning of string which results to an error (undefined index). Trimmed those spaces to solve the issue.
=> Update SVGPolygonalShape.php, trimm points attribute from trailing spaces

src/Nodes/Shapes/SVGRect.php, src/Rasterization/Renderers/SVGRectRenderer.php
Adds support for the `rx` and `ry` attributes on the `<rect>` element.
* The `SVGRect` class receives new getters and setters for those attributes.
* `SVGRectRenderer` is adapted to support rendering the rounded corners.
=> Add support for rounded rectangles based on #29

src/Nodes/SVGNode.php, src/Nodes/Texts/SVGText.php, src/Nodes/Texts/SVGTextPath.php, src/Reading/SVGReader.php, src/Writing/SVGWriter.php
9a490f7 : Allows to retrieve the value of a xml tag ([see __toString of \SimpleXMLElement](http://php.net/manual/en/simplexmlelement.tostring.php))
cf6c017 : Add node text and textPath (do not implement rasterize)
=> Returns text content that is directly in this element.

src/Nodes/Texts/SVGTitle.php, src/Reading/SVGReader.php, src/Writing/SVGWriter.php
There are many use-cases for this library where one is actually more in the SVG itself than in the rasterized image-file.
In these use-cases, it might be nice to have a simple mouse-over text over some elements of the SVG. The [`<title>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) element implements that functionality.
This pull request further fixes an possible xss attack in the text nodes and refactors the `writeNode` method.
=> Add title type

README.md
This PR adds a link to the wiki at the bottom of README.md. It took me an hour or two of using the software and trying to figure out how to draw shapes with it, before I discovered the additional documentation in the wiki. By adding this link I hope to make the wiki more apparent to new users. That will in turn hopefully result in more edits to the wiki, to further improve the docs.
=> Add link to Wiki for additional documentation

.travis.yml
See #94. This is not a foolproof solution, as failure is random with chance 0.X and this simply reduces it to (0.X)^3. It should be good enough in most cases though.
=> Prefix Travis install with travis_retry (fixes #94)

src/Reading/AttributeConverter.php, src/Reading/LengthAttributeConverter.php, src/Reading/SVGReader.php, tests/Reading/LengthAttributeConverterTest.php, tests/Reading/SVGReaderTest.php
Fixes #96 
**Background info:**
SVG allows some presentation attributes, for example `font-size`, to be specified without a unit; like this:
```xml
<text font-size="11">foo</text>
```
The same would not be valid in CSS, where a unit is required; like this:
```xml
<text style="font-size: 11px">foo</text>
```
**Reason for this PR:**
PHP-SVG merges attributes and style properties during reading. In that process, once valid attributes can become invalid CSS properties. This PR fixes that by adding value conversion facilities.
=> Add converter for unitless lengths during read

src/Nodes/Structures/SVGDocumentFragment.php, src/Reading/SVGReader.php, src/SVG.php, tests/SVGTest.php
Sometimes, it might be required to create an SVG with no width/height. The width/height arguments of `SVGDocumentFragment` are already optional. This PR is making them optional for `SVG` too. Note that not providing dimensions potentially hinders rasterization.
=> Make SVG dimension parameters optional

src/Nodes/Shapes/SVGPolygonalShape.php, tests/Nodes/Shapes/SVGPolygonTest.php, tests/Nodes/Shapes/SVGPolygonalShapeTest.php, tests/Nodes/Shapes/SVGPolylineTest.php
This PR serves to remove the need for `constructFromAttributes` on `SVGPolygonalShape`. It replaces the separate `$points` property with code that dynamically accesses the `points` attribute. This should also help with eliminating pitfalls such as property and attribute getting out of sync.
=> Make SVGPolygonalShape points dynamic

src/Nodes/CDataContainer.php, src/Nodes/SVGNode.php, src/Nodes/SVGNodeContainer.php, src/Nodes/Structures/SVGScript.php, src/Nodes/Structures/SVGStyle.php, src/Reading/NodeRegistry.php, src/Writing/SVGWriter.php, tests/Nodes/SVGNodeContainerTest.php, tests/Nodes/SVGNodeTest.php, tests/Nodes/Structures/SVGScriptTest.php, tests/Nodes/Structures/SVGStyleTest.php, tests/Reading/SVGReaderTest.php, tests/Utilities/SVGStyleParserTest.php, tests/Writing/SVGWriterTest.php
* `constructFromAttributes` was used basically nowhere, a remnant of the past. All it did was cause confusion. This PR removes it entirely.
* Moreover, style and script CDATA handling is given an overhaul, which was required by (1).
* Last but not least, misplaced `SVGStyleParser` tests are moved to their own file.
=> Eliminate constructFromAttributes

src/Reading/NodeRegistry.php, src/Reading/SVGReader.php, tests/Reading/NodeRegistryTest.php
The need to pass a `SimpleXMLElement` to `NodeRegistry::create` was eliminated with PR #106. This PR now simplifies the interface accordingly, to only require a string type instead of a full-blown element.
=> Change NodeRegistry::create to use string

.github/workflows/php.yml, LICENSE, README.md, tests/bootstrap.php
Travis has become effectively unusable for Open Source. This PR moves us to GitHub Actions.
Note that I initially included testing on PHP v8.0, in addition to the existing versions. Unfortunately PHP-SVG is not yet compatible with PHP 8. Therefore tests failed, which meant that the new Actions workflow could not be observed in its entirety. As the workflow is the main contribution of this PR I decided to remove testing PHP 8 and will add it again later.
=> Move to GitHub Actions

.github/workflows/php.yml, .gitignore, LICENSE, composer.json, src/Rasterization/Renderers/ImageRenderer.php, tests/Rasterization/Renderers/MultiPassRendererTest.php, tests/Rasterization/SVGRasterizerTest.php, tests/SVGTest.php
Adds a job for PHP 8 to the test workflow. Also removes staggered execution
of the workflows, so that all of PHPCS, tests, and coverage can execute
immediately.
Dev dependency meyfa/phpunit-assert-gd is updated from v1.1 to v1.2 for
PHP 8 support.
ImageRenderer and a few test cases are adapted to treat `\GdImage` on PHP 8
the same as gd resources on earlier PHP versions.
=> chore(ci): Configure test workflow to also run on PHP 8

src/Nodes/Shapes/SVGPath.php, src/Rasterization/Renderers/PathRenderer.php, src/Rasterization/Renderers/PathRendererEdge.php, src/Rasterization/SVGRasterizer.php, tests/Nodes/Shapes/SVGPathTest.php
Fixes #28. The time has finally come that I understand how scanline
algorithms work and was able to implement this by referencing an
existing implementation in the SerenityOS path renderer.
I did a lot of work to adapt that code to PHP and get it to perform as
well as possible. Note that for some images rendering still takes ages,
but that is not due to PathRenderer, rather the BezierApproximator does
not yet take scale into account and oftentimes generates curves with
waaaaay too many segments. I have done benchmarks and this rendering
algorithm is insanely efficient for what it does. If anything can be
optimized, it is probably the looping over and transforming of each
point during preparation.
=> feat: Implement path rendering that respects fill-rule! :)

src/Rasterization/Renderers/EllipseRenderer.php, src/Rasterization/Renderers/LineRenderer.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/Renderers/PathRenderer.php, src/Rasterization/Renderers/PolygonRenderer.php, src/Rasterization/Renderers/RectRenderer.php, src/Rasterization/Renderers/Renderer.php
PHP simply cuts off any decimal part of the stroke width. I have just
come across an example where the stroke width that was expected to be
rendered was 1.99999997 pixels, but of course that meant only 1 pixel
wide was actually rendered. With this change, that problem should be
gone. Until we have antialiasing, it's probably fine to assume any
stroke width of greater than or equal to 1.5px should become 2px.
=> fix: Round the strokeWidth when outlining shapes in renderers

src/Rasterization/Transform/Transform.php, tests/Rasterization/Transform/TransformTest.php
This class will of course be used for more elegant mapping from SVG
space into raster space. More importantly, by chaining additional
calls to the transform operations during tree walking whenever a
transform attribute or style is encountered, full transform support can
be added. Note that this is not yet implemented.
=> feat: Implement a Transform class

src/Rasterization/SVGRasterizer.php, tests/Rasterization/SVGRasterizerTest.php
These will be useful for spec-compliant computation of length
percentages, for attributes that do not refer to a specific axis.
Currently, we are using the document width as reference for everything.
=> feat: Add normalized diagonal getters to SVGRasterizer

src/Utilities/Units/Length.php, tests/Utilities/Units/LengthTest.php
This behavior is very useful for converting length attributes that are
optional. We should ensure it doesn't go away, so that callers can
depend on it.
=> tests: Ensure Length::convert() with null input returns null

src/Nodes/Embedded/SVGImage.php, src/Nodes/Shapes/SVGCircle.php, src/Nodes/Shapes/SVGEllipse.php, src/Nodes/Shapes/SVGLine.php, src/Nodes/Shapes/SVGRect.php, src/Nodes/Texts/SVGText.php, src/Rasterization/Renderers/EllipseRenderer.php, src/Rasterization/Renderers/ImageRenderer.php, src/Rasterization/Renderers/LineRenderer.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/Renderers/RectRenderer.php, src/Rasterization/Renderers/Renderer.php, src/Rasterization/Renderers/TextRenderer.php, tests/Nodes/Embedded/SVGImageTest.php, tests/Nodes/Shapes/SVGCircleTest.php, tests/Nodes/Shapes/SVGEllipseTest.php, tests/Nodes/Shapes/SVGLineTest.php, tests/Nodes/Shapes/SVGRectTest.php, tests/Rasterization/Renderers/RectRendererTest.php
This allows for a better separation of concerns between nodes and
renderer implementations. Now, the renderers always get resolved pixel
values for all their position and length inputs. This means they only
have to care about transforming the coordinates into the render target
coordinate space by scaling and offsetting, and not have to care about
resolving strings with units against viewport lengths.
Regarding the last point: The spec clearly states that lengths for
properties such as 'ry', 'height' etc. must be resolved against the
document height instead of width. This is now fixed. Others, such as
'stroke-width' or 'r' need to be resolved against the diagonal.
This also makes this change somewhat mandatory: The 'ellipse' renderer
cannot know whether to resolve both 'rx' and 'ry' …
=> refactor: Convert lengths to pixels outside of renderers

src/Rasterization/Transform/Transform.php, tests/Rasterization/Transform/TransformTest.php
This method is currently unused, but will be useful later when
implementing transform support for shapes.
=> feat: Add resize() method to Transform for measuring width/height scale

src/Rasterization/Renderers/EllipseRenderer.php, src/Rasterization/Renderers/ImageRenderer.php, src/Rasterization/Renderers/LineRenderer.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/Renderers/PathRenderer.php, src/Rasterization/Renderers/PolygonRenderer.php, src/Rasterization/Renderers/RectRenderer.php, src/Rasterization/Renderers/TextRenderer.php, src/Rasterization/SVGRasterizer.php, tests/Rasterization/Renderers/MultiPassRendererTest.php, tests/Rasterization/SVGRasterizerTest.php
SVGRasterizer::makeTransform() is added to obtain a Transform object
representing the mapping of userspace coordinates into image
coordinates, just like it was previously done manually by scaling and
then translating every coordinate inside the renderers. These
computations can now be replaced by simple calls to Transform::map and
related methods.
By doing this, the MultiPassRenderer::prepareRenderParams() method does
not even need access to the SVGRasterizer anymore.
Note that handling of the `transform` attribute or style is not part of
this change.
=> refactor: Use Transform class for viewport scale+offset during render

src/Rasterization/Path/PathApproximator.php, src/Rasterization/Transform/TransformParser.php, tests/Rasterization/Transform/TransformParserTest.php, tests/Rasterization/Transform/TransformTest.php
This class provides a static method parseTransformString() for parsing
strings such as 'translate(10,20) rotate(45)' into Transform objects.
This new method will be used later, when implementing support for node
transforms in rendering. That feature is not part of this patch though.
=> feat: Implement TransformParser for converting strings to Transform

src/Nodes/Embedded/SVGImage.php, src/Nodes/SVGNodeContainer.php, src/Nodes/Shapes/SVGCircle.php, src/Nodes/Shapes/SVGEllipse.php, src/Nodes/Shapes/SVGLine.php, src/Nodes/Shapes/SVGPath.php, src/Nodes/Shapes/SVGPolygon.php, src/Nodes/Shapes/SVGPolyline.php, src/Nodes/Shapes/SVGRect.php, src/Nodes/Texts/SVGText.php, src/Rasterization/Renderers/ImageRenderer.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/SVGRasterizer.php, tests/Rasterization/SVGRasterizerTest.php
The rasterizer obtains a transform stack, which initially contains just
the viewport scale+offset transform. The new methods for pushing to and
popping from that stack are intended to be used by nodes during render.
If a node has a 'transform' attribute, it can call `pushTransform()`,
apply its own transform on top of the previous one, do its rendering
with that, and finally call `popTransform()` to revert to the previous
transform state so that its siblings and ancestors can render correctly
as well.
I also considered passing the parent transform to each node as an
argument of the `SVGNode::rasterize()` method, but that seemed very
messy because we'd have to remember for every node class to properly
clone the transform before mutating it. With this design, there will
still be code …
=> feat: Add SVGRasterizer::pushTransform() and ::popTransform()

src/Rasterization/Path/PathApproximator.php, src/Rasterization/Renderers/PathRenderer.php, tests/Rasterization/Path/PathApproximatorTest.php
PathApproximator is already keeping some state such as $previousCommand
that is only valid for the currently-processed path. There is the risk
of unexpected results when rendering multiple paths in a row, where the
later paths are affected by state that was not properly reset. By making
the class be explicit about its stateful nature and requiring one
instance per path data, these problems are avoided.
=> refactor: Make PathApproximator explicitly stateful

.github/workflows/php.yml
Since we are not committing composer.lock, it makes no sense to use it
as the cache key. The docs for the setup-php action also mention that
we can just use composer.json for key computation instead, in that case.
=> chore(ci): Use composer.json for cache key instead of composer.lock

.github/workflows/php.yml
According to setup-php's documentation, caching "vendor" directly will
have side effects, and we should use composer's internal cache directory
instead.
=> chore(ci): Cache composer's internal cache directory instead of vendor

src/Rasterization/Path/ArcApproximator.php, src/Rasterization/Path/BezierApproximator.php, src/Rasterization/Path/PathApproximator.php, src/Rasterization/Renderers/PathRenderer.php, tests/Rasterization/Path/PathApproximatorTest.php
Fixes #86. Instead of approximating the path first and *then* mapping
the resulting points into image space, they are mapped into image space
first, and then approximated. This means there is exactly the right
amount of visual fidelity, independent of the relationship between path
coordinate space and image coordinate space. If the image is scaled up,
the approximation simply gets more detailed, and if the image is scaled
down, the approximation will also contain fewer points to improve
performance.
This works very nicely for lines and Bézier curves which are invariant
under affine transforms, i.e., there is no downside to changing the
order of operations like this. Yet, I still don't know how to apply the
idea to arcs, which might not be invariant, at least not in SVG's
endpoint …
=> feat: Rewrite PathApproximator to take the Transform into account

src/Rasterization/Renderers/MultiPassRenderer.php, tests/Rasterization/Renderers/MultiPassRendererTest.php
Closes #117. In addition to implementing these two attributes, parsing
of the 'opacity' attribute is also improved: It can now deal with
whitespace surrounding the value, and with percentages.
=> feat: Implement renderer support for 'fill-opacity' and 'stroke-opacity'

src/Nodes/SVGNode.php, src/Nodes/Shapes/SVGPath.php, src/Nodes/Shapes/SVGPolygon.php, src/Nodes/Shapes/SVGPolyline.php, src/Rasterization/Renderers/MultiPassRenderer.php, tests/Nodes/SVGNodeTest.php, tests/Nodes/Shapes/SVGPathTest.php, tests/Nodes/Shapes/SVGPolygonTest.php, tests/Nodes/Shapes/SVGPolylineTest.php
Fixes #160. SVGNode::setStyle is modified to trim the input before
storing it, effectively guaranteeing that styles never have leading or
trailing whitespace. Tests are added and/or adapted to look out for this
behavior. Some code could be simplified by removing manual trimming
after retrieval of the style value, since this is no longer needed.
=> fix: Ensure style properties do not contain surrounding whitespace

src/Rasterization/Renderers/PathRendererImplementation.php, tests/Rasterization/Renderers/PolygonRendererTest.php
PR #164 fixed a path and polygon crash when filling shapes that have too few points in them.
This PR fixes a potential crash when drawing the stroke in these scenarios.
(That should have been part of the previous PR, but was not noticed due to a mistake in the unit test.)
=> fix: Avoid path stroke crash with too few points

LICENSE, README.md
The introductory section is rewritten with better wording. A disclaimer
about PHP-SVG still being in the alpha stage is added.
Installation requirements are now specified.
A link to the old master branch is fixed to point to 'main' instead.
The contributing section is moved to the end of the README and
completely rewritten to be more helpful and welcoming to new
contributors.
The wiki content is merged into the "Getting started" section.
A download count badge is added.
=> docs(readme): Rewrite the README (fixes #125)

src/Nodes/SVGNode.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/Transform/TransformParser.php
With php8.1 comes deprecation-warnings.
`Passing null to parameter of type string is deprecated`
I have fixed these who appeared on my website.
=> fix: Avoid deprecation warnings when passing null

src/Rasterization/Path/ArcApproximator.php
Formerly sqrt(x*x, y*y) was used. This has been replaced with PHP's native function hypot(). Fixes meyfa/php-svg#140.
=> refactor: Use hypot() to calculate hypotenuse

src/Nodes/SVGNode.php, src/Nodes/SVGNodeContainer.php, src/Nodes/Shapes/SVGPolygonalShape.php, src/Rasterization/Path/PathParser.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Shims/Str.php, src/Utilities/Colors/Color.php, src/Utilities/SVGStyleParser.php, src/Writing/SVGWriter.php, tests/Shims/StrTest.php
- Added \SVG\Shims\Str::trim() that accepts null as an argument as this is deprecated for PHPs native trim() as of PHP 8.1.
- Replaced all instances of trim() for the newly added shim.
=> fix: Add shim for trim() that accepts null

src/Nodes/SVGNode.php, src/Rasterization/Path/PolygonBuilder.php, src/Rasterization/Renderers/PolygonRenderer.php, src/Rasterization/Transform/TransformParser.php
The coalescing operator is available since PHP 7. Since we now have a minimum version requirement of 7.3 (see PR #182), we can simplify some code by using it.
=> fix: Use the coalescing operator `??`

src/Reading/SVGReader.php, tests/Reading/SVGReaderTest.php
Fixes #109. We don't support PHP 5.3 anymore due to PR #182, so the TODO can safely be removed, along with the `@requires` on associated tests.
=> chore: Remove TODO about PHP version 5.3 missing a parameter

README.md
As discussed in #187 older versions were dropped and support for PHP 8.1 and 8.2 was added. Updated README to also mention newer versions.
=> chore: update README, add newer PHP versions

src/Nodes/Structures/SVGDocumentFragment.php, src/Nodes/Texts/SVGText.php, tests/Nodes/Structures/SVGDocumentFragmentTest.php, tests/Nodes/Texts/SVGTextTest.php
=> fix: Set a default font-size

src/Rasterization/Renderers/EllipseRenderer.php, src/Rasterization/Renderers/LineRenderer.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/Renderers/PathRenderer.php, src/Rasterization/Renderers/PolygonRenderer.php, src/Rasterization/Renderers/RectRenderer.php, src/Rasterization/Renderers/TextRenderer.php, tests/Rasterization/Renderers/TextRendererTest.php
The text renderer would previously throw in some circumstances if no font was available. With this patch, its `prepareRenderParams()` method can return `null` in these cases, aborting the render for that text element without causing a crash.
This also simplifies RectRenderer, which doesn't need an "empty" state anymore.
=> fix: Allow renderer short-circuit if unable to render anything

src/Rasterization/Renderers/RectRenderer.php
Resolves https://github.com/meyfa/php-svg/issues/203
=> RectRenderer: For undefined x and y attributes use 0 as default value

src/Rasterization/Renderers/EllipseRenderer.php
Fixed default ellipse properties according to SVG specification https://www.w3.org/TR/SVG2/geometry.html
=> fix: Apply defaults for cx, cy, rx, ry in EllipseRenderer

src/Nodes/SVGNode.php, src/Nodes/SVGNodeContainer.php, src/Nodes/Structures/SVGDocumentFragment.php, src/Rasterization/Path/PolygonBuilder.php, src/Rasterization/Renderers/MultiPassRenderer.php, src/Rasterization/SVGRasterizer.php, src/Rasterization/Transform/TransformParser.php, src/SVG.php, src/Utilities/Colors/Color.php, src/Writing/SVGWriter.php
Another set of small improvments:
* Use`===` over `==`
* Use strict types over `isset` or `empty`
* Use spreads over `array_merge` (better performance)
* Use multiline docblocks over inlined
=> fix: Improve PHP syntax

src/Fonts/FontRegistry.php, src/Fonts/TrueTypeFontFile.php, src/Rasterization/Renderers/TextRenderer.php
=> feat: Support rendering 'Oblique' fonts

.github/workflows/php.yml, README.md
PHP 8.4 currently has RC4 out, actual release will be later this month. You may want to wait with merging this until 21-11-2024, although I suspect not much will change in the mean time that's relevant to this project.
Please note that `composer.json` requires no changes, hence a release for this PR will not be necessary as users will already be able to install latest release on PHP 8.4. This PR just makes sure future changes are also tested on PHP 8.4.
=> chore: Update CI to run tests on PHP 8.4

src/Nodes/SVGNodeContainer.php, src/Nodes/Shapes/SVGPath.php, src/Nodes/Shapes/SVGPolygonalShape.php, src/Nodes/Structures/SVGClipPath.php, src/Rasterization/Transform/TransformParser.php
Fix `Deprecated: SVG\Nodes\Structures\SVGClipPath::__construct(): Implicitly marking parameter $id as nullable is deprecated, the explicit nullable type must be used instead` and more
=> fix: Fix PHP 8.4 deprecations

phpunit.xml
Changes PHPUnit config to:
- Enable error reporting
- Error on deprecation warnings
Note that due to PHPUnits way of parsing warnings, not all deprecations may lead to errors.
---
Currently, PHPUnit is not properly configured to report deprecation warnings, as noted in [#241](https://github.com/meyfa/php-svg/issues/241#issuecomment-2677872751). This means that while our CI tests pass, they do not catch potential future breakages introduced by deprecated functionality.  
Deprecation warnings:  
- **Are early indicators** of breaking changes in future PHP versions.  
- **Can clutter production logs**, potentially causing unnecessary noise for users.  
- **Have been historically reported as runtime bugs** in this repository ([#173](https://github.com/meyfa/php-svg/issues/173), …
=> chore: Let PHPUnit convert deprecations to errors
